### PR TITLE
closes #137, permit to have @FindBy with a FluentList, can potentialy br...

### LINKED ISSUE #137: FluentList does not work wit @FindBy initialisation
The FluentList class attribut is not initialized with @FindBy annotation.

It is alwoas null.

### PR DESCRIPTION
**Pull request by twillouer**
can potentialy break compatibilitiy : FluentList is now an interface (to be proxyfied). Not sure than this is the best solution, any idea ?

### CODE REVIEW

**Comment by j-walker23** [comment]
This would be awesome, is it ready to go?

**Comment by j-walker23** [comment]
@twillouer Is there any way to use this without it being merged yet? This is a great feature, thanks for taking the time.

**Comment by twillouer** [comment]
@j-walker23 mvn clean install on my branch, change your pom to snapshot :)

And it will be nice to have a real test !

**Comment by j-walker23** [comment]
@twillouer perfect thanks man, i will do that

**Comment by MathildeLemee** [comment]
Thanks.

**Pull request merged**
