### PR TITLE
Feature/spock support

### PR DESCRIPTION
**Pull request by jarlehansen**
Creating a new pull request with the feature/spock-support branch. I fixed a few issues with duplicate dependencies and the problem with the ${java.version} that was not working in the junit and testng modules.

In addition to adding the `FluentSpecification` and `FluentSpecificationAdapter` I have added unit tests in fluentlenium-spock/src/test/groovy (influenced by the setup in cucumber) and also an example using Spock in the examples folder.

The documentation is updated with a short explanation (similar to the one for testng) on how to use Spock.

### CODE REVIEW

**Comment by filipcynarski** [comment]
Thank you @jarlehansen !

**Comment by filipcynarski** [comment]
@jarlehansen do you think this feature is ready?

**Comment by filipcynarski** [comment]
${java.version} shouldn't work in examples indeed because there is no parent to inherit from. In junit module it should work I'll add it again.

**Comment by jarlehansen** [comment]
At least ready for some feedback, thanks for merging @filipcynarski

**Comment by filipcynarski** [comment]
thank you! I'll try to use it.

**Pull request merged**
