### PR TITLE
ensure to compile the gradle example tests

### PR DESCRIPTION
**Pull request by abendt**
the gradle task compileKotlin does not compile the example tests, we need to use a different gradle task

### CODE REVIEW

**Comment by slawekradzyminski** [comment]
@abendt perhaps not related but do you know why this job:
https://github.com/FluentLenium/FluentLenium/runs/2877299001

fails to find mentioned libraries after selenium bump to **4.0.0-beta-4**?

```
Could not find netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar (io.netty:netty-transport-native-epoll:4.1.63.Final).
Searched in the following locations:
    file:/Users/ocado/.m2/repository/io/netty/netty-transport-native-epoll/4.1.63.Final/netty-transport-native-epoll-4.1.63.Final-linux-x86_64.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by abendt** [comment]
> @abendt perhaps not related but do you know why this job:
> https://github.com/FluentLenium/FluentLenium/runs/2877299001

will have a look later

**Comment by abendt** [comment]
> fails to find mentioned libraries after selenium bump to **4.0.0-beta-4**?

think i understand now whats going on:

webdriver 4 has a transitive dependency on some jars that use classifiers:
https://search.maven.org/artifact/org.asynchttpclient/async-http-client/2.12.3/jar
```
<dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-epoll</artifactId>
      <classifier>linux-x86_64</classifier>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-kqueue</artifactId>
      <classifier>osx-x86_64</classifier>
    </dependency>
```

It seems that gradle has some issues resolving artifacts with classifiers from local repositories: https://github.com/gradle/gradle/issues/15756

this seems to be the reason why the build fails, you can also reproduce this locally ...

**Comment by slawekradzyminski** [comment]
thanks :)

**Pull request merged**
