### PR TITLE
#617 - Add FluentWebElement based methods to SearchControl

### PR DESCRIPTION
**Pull request by picimako**
I'm not sure I got the essence of the task. Please have a look.

### CODE REVIEW

**Comment by slawekradzyminski** [comment]
Hi @picimako I haven't checked the code yet but I'd like to verify my yesterday's CI changes are working well. Can you please update .travis.yml file on your branch?

There is no Coveralls and Travis run attached here.

**Comment by slawekradzyminski** [comment]
Ok @picimako looks like Travis would migrate us soon to new platform (travis-ci.com). It's ok that it didn't run ;)

**Comment by slawekradzyminski** [comment]
@picimako can you add integration tests to show it in action? I believe the goal was to reuse locators:

```java
@Test
public void test() {
goTo(page);
FluentList<FluentWebElement> list = $("css.selector);
FluentList<FluentWebElement> secondList = $(list.getLocator());
}```

Do we have common understanding?

**Comment by picimako** [comment]
@slawekradzyminski 
My understanding of *to put already created FluentWebElement in $() and el() methods* is to have a variant of these methods that can accept a `FluentWebElement` or a list of them as argument. As I see both in `FluentListImpl` and `FluentWebElement` the `ElementLocator` for hookcontrol is essentially created from the underlying `WebElement` or list of WebElements, and is not stored permanently.

In case of your example my understanding is that we should make the ElementLocator accessible, and initialize the `FluentWebElement` or `FluentList` based on another object's ElementLocator.

In any case, it would be good if @koryl provided a code example of what he imagined in that feature request.

**Comment by picimako** [comment]
@slawekradzyminski I checked #597 and that #617 is now closed as a duplicate.
I'm a little bit confused what the actual task is now. In my understanding of #597 currently the task is to implement FluentWebElement#getSelector() method returning the String selector of that element.

If that's correct, I'm going to close this PR so that it won't confuse anyone, and you are feel free to delete the branch.

**Comment by slawekradzyminski** [comment]
Hi @picimako,

Yes you can close this PR. Thanks for effort, but we need getSelector() returning By and integrationa tests to show it in action.

**Pull request closed without merging**
