### PR TITLE
Feature/#599 remove deprecated api usage

### PR DESCRIPTION
**Pull request by picimako**

### CODE REVIEW

**Comment by slawekradzyminski** [comment]
Hi @picimako thanks for submission.

Considering you want to actively contribute here I'd like you to fix few things:
1. You are adding maven dependency into fluentlenium-core which we generally try to avoid in order to make FluentLenium as independent as possible.
2. The task was aimed to remove deprecated API, but you haven't touched MouseActions and KeyboardActions classes which use Mouse and Keyboard classes deprecated by Selenium
3. You change a lot of lines for no particular reason (like rearranging imports), please try to avoid such changes, especially during feature work.

Merge request can't be accepted in this form. Please fix points 2 and 3 as a must and maybe 1 as well.

**Comment by picimako** [comment]
@slawekradzyminski 

Thank you for your comments. I do want to actively contribute as my free time allows me to do so.

I also wanted to clarify a few things.
1. I added the new dependency so that the recommended version of `StringEscapeUtils` can be used from commons-text, instead of the deprecated version from commons-lang3 in `CssSupportImpl`.
2. I'm still working on the Mouse and Keyboard part, however it is not entirely clear what I should do.
Should I remove the method `basic()` from both `MouseActions` and `KeyboardActions` and rely solely on the `Actions` class, or should I just mark the method as deprecated for now, and will be removed in a later release?
3. Valid point. The import reorders were done automatically by IntelliJ but I can revert them.
I also wanted to propose adding the import order in `dev-config/idea/code-style.xml` so there would be a unified config for that as well.
Currently I'm using the following settings based on https://google.github.io/styleguide/javaguide.html#s3.3-import-statements:
```
import static all other imports
<blank line>
import org.fluentlenium.*
import all other imports
import java.*
import javax.*
```

**Comment by slawekradzyminski** [comment]
Thanks @picimako - I'll add a task for checkstyle investigation

**Comment by slawekradzyminski** [comment]
@picimako please send me an email - it's in pom.xml

**Pull request merged**
