### PR TITLE
Feature/#770 refactor events and listener classes

### PR DESCRIPTION
**Pull request by picimako**

### CODE REVIEW

**Comment by slawekradzyminski** [comment]
Thanks @picimako :)

Any chance for integration tests that would show this feature in action?

**Comment by tamasbalog** [comment]
@slawekradzyminski 
Good point. I will look around in the integration tests module and see what I can do.

**Comment by slawekradzyminski** [comment]
There is also a question awaiting for an answer. Would you be able to help?
https://github.com/FluentLenium/FluentLenium/issues/737

**Comment by picimako** [comment]
I will also check #737 if I can answer that.

**Comment by slawekradzyminski** [comment]
@picimako would you be able to push it into our repo? Can be the same branch **feature/#770-refactor-events-and-listener-classes**

You have rights to do that :)

**Comment by picimako** [comment]
@slawekradzyminski 
Do you mean to push it directly into this repo and not use the fork? That actually makes sense. :)

Is it ok if I close both of my PRs and reopen them from the new branches?

**Comment by slawekradzyminski** [comment]
@picimako yes, you can close it and reopen from FluentLenium directly.

**Pull request merged**
