### PR TITLE
#715: Add funcitonality to retrieve values based on the W3C Performan…

### PR DESCRIPTION
**Pull request by picimako**
…ce Timing API

### CODE REVIEW

**Comment by slawekradzyminski** [comment]
Hi @picimako 

I noticed two issues:
1. Conversion to TimeUnit doesn't work.
2. If the event hasn't been registered during the call we print 0. Perhaps we should wait for it?

Details in my commit.

Also: 
1. Please extend unit tests coverage, -0,6% is rather disappointing result.
2. Please add E2E test example and link it in documentation. Users would like to know how to actually use this feature.

**Comment by picimako** [comment]
@slawekradzyminski 
1. I'm a bit confused. Where did you run into that? I added unit tests to specifically check TimeUnit conversion and they seemed to be working properly.

2. Hmm, that's interesting. I'll check whether
- this is something that SafariDriver handles differently
- that the event indeed haven't been registered at some point.
- or the page just hasn't loaded completely yet (the api returns 0 for that as well)

If the latter one is the case, I think it could even be the user's responsibility to wait for a page to load completely and retrieve the values only after that. (However this may cause issues in the future when we implement the performance reporting.)
What do you think?

3. I think I covered every crucial logic with unit tests but I'll check what I can do to increase the coverage.

4. I added an integration test but I'll definitely extend it with a couple more use cases. And will add info about that to the documentation as well.

**Comment by slawekradzyminski** [comment]
@picimako steps to reproduce are in my commit :) https://github.com/FluentLenium/FluentLenium/pull/874/commits/8f921b064c39657fb3e7d33ac634676513891d07

**Comment by picimako** [comment]
@slawekradzyminski 
I think that value is correct. As I've seen the value returned by the browsers is in milliseconds.

With this e2e test I get the following results:

```java
@Test
    void duckduckgo() {
        goTo("https://duckduckgo.com");

        System.out.println(performanceTiming().loadEventStart());
        System.out.println(performanceTiming().loadEventStart(TimeUnit.SECONDS));
    }
```

1562604372585
1562604372

The first one is the default millisecs, the other the converted one, and they both show today's date if I convert them to human readable format: https://www.epochconverter.com

**Comment by slawekradzyminski** [comment]
Would it be possible to to get rid of epoch time? navigationStart event should be our starting point (0s).

**Comment by picimako** [comment]
@slawekradzyminski 
It would be possible but I think it would also be (a bit) confusing for end users what values are returned and why. I think the current format might give them greater flexibility to work with, and they could implement their own performance calculations based on the values provided by/via FL.

I also think that we should wait whether this feature is something that users would actually use in this format, and if there is a need for more complex performance queries we could extend the current solution.

**Comment by slawekradzyminski** [comment]
@picimako I disagree with you. For me `1562399425` load event value is totally useless as an end user

**Comment by picimako** [comment]
@slawekradzyminski 
Just to make sure that we have the same understanding on what should be done because I have two understandings for what you proposed.

1. We should provide custom metrics for users, like how much time did it take from `fetchStart` to `domainLookUpEnd` or from `redirectEnd` to `connectEnd`, which I don't think is a scope of FluentLenium.

2. The other, which I think is more likely what you are proposing, is that we should simply handle/convert the value of `navigationStart` to zero and calculate the other metrics relatively to this value. If you mean this, I am totally in, and I can rework my PR based on this.

**Comment by slawekradzyminski** [comment]
Yes, if you take a look at my blog post you can see an example:

```java
  private long getLoadTimeInSeconds(long loadEventEnd, long navigationStart) {
        long loadTimeInSeconds = (loadEventEnd - navigationStart) / 1000;
        String logBody = String.format("Page Load Time is %s seconds.", loadTimeInSeconds);
        System.out.println(logBody);
        return loadTimeInSeconds;
    }```

**Pull request merged**
