### PR TITLE
resolves #241, locatable issue

### LINKED ISSUE #241: FluentWebElement created by @FindBy annotation is not able to receive doubleClick and mouseMove Webdriver Action
FluentWebElement created by @FindBy annotation is not able to receive doubleClick and mouseMove Webdriver Action

```
java.lang.ClassCastException: com.sun.proxy.$Proxy26 cannot be cast to org.openqa.selenium.internal.Locatable

	at org.openqa.selenium.interactions.Actions.moveToElement(Actions.java:257)
	at org.fluentlenium.core.action.MouseActions.mouseOver(MouseActions.java:17)
	at org.fluentlenium.core.domain.FluentWebElement.mouseOver(FluentWebElement.java:88)
	at com.lastmile.system.tests.engine.webshop.page.LoggedOutPage.clickLoginLink(LoggedOutPage.java:31)
	at com.lastmile.system.tests.engine.webshop.WebshopFluentTest.loginUser(WebshopFluentTest.java:57)
	at com.lastmile.system.tests.scenario.AddItemsToBasketIT.BookSlot(AddItemsToBasketIT.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at com.lastmile.system.tests.engine.webshop.engine.listener.NeedsCustomerRule$1.evaluate(NeedsCustomerRule.java:56)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:254)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

```

### PR DESCRIPTION
**Pull request by filipcynarski**
This issue resolves issues related to actions which may require Locatable interface to be implemented

### CODE REVIEW

**Comment by Toilal** [comment]
Maybe the previous bug could be tested in a unit test ?

**Comment by filipcynarski** [comment]
Well, it is worth to write a unit test for that.

**Comment by filipcynarski** [comment]
Test added.

**Comment by Toilal** [comment]
:+1: Thanks ! great, LGTM (when build is over)

**Pull request merged**
