### PR TITLE
Selenium 4 Support

### PR DESCRIPTION
**Pull request by abendt**
This is based off the PR https://github.com/FluentLenium/FluentLenium/pull/1084

I have added all necessary changes to compile and run tests
with  selenium 4.0.0

upgrade selenium version to 4.0.0
fixes to some tests that were failing
contains a Workaround for a weird NoClassDefFoundError i was seeing: https://github.com/FluentLenium/FluentLenium/pull/1356/files#diff-59b2e8d00ff09cf8abd4fa71e55d5f7c560697921a4285790ddb4b8a87ce8ab1R20

### CODE REVIEW

**Comment by slawekradzyminski** [comment]
@abendt do you know if Appium test works? :)

**Comment by abendt** [comment]
> @abendt do you know if Appium test works? :)

hi @slawekradzyminski,

thanks for pointing out the appium examples, i was not aware of them.
i needed to make some more changes to allow the appium related code to be compiled (see commit right before this comment).

I do not have any experience setting up appium locally to be able to run the examples, so i don't know if it will actually work with appium. will see if i find some time to dig deeper into the required setup

**Comment by abendt** [comment]
hi @slawekradzyminski,

with some help from a former colleague we could confirm that the Appium based example works (thanks @Jose-Luis-Nunez). We tried out the Android example.

The example itself does not work out of the box, we might prepare another PR to suggest some changes for easier usage.

**Comment by slawekradzyminski** [comment]
So we are good to go. @abendt will you merge untilAsserted and library bumps as well? Perhaps next week I’ll reserve myself some time to create a release

**Comment by slawekradzyminski** [comment]
Poor shadom dom supports remains as the only major issue.

**Comment by abendt** [comment]
> So we are good to go. @abendt will you merge untilAsserted and library bumps as well? Perhaps next week I’ll reserve myself some time to create a release

great.

yes, will prepare everything

**Comment by abendt** [comment]
https://github.com/FluentLenium/FluentLenium/issues/1372

**Pull request merged**
